---
- name: install httpd using when condition-playbook
  hosts: all
  become: true
  tasks:
# install app and start service -RedHat
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family=="RedHat"
    tags: install_app
  - name: start service httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"  
    tags: start_service

# install app and start service - ubuntu
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
    tags: install_app
  - name: start service apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"  
    tags: start_service
# copy index.html file
  - name: copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0777

