---
- name: install httpd using when condition-playbook
  hosts: all
  become: true
  tasks:
# tasks setup to install apache2 and redhat
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family=="RedHat"
    notify: start service httpd
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
    notify: start service apache2
  - name: copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0777


# handlers section

   handlers:
  - name: start service httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat" 
  - name: start service apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"  

