---
- name: uninstall httpd using when condition-playbook
  hosts: all
  become: true
  tasks:
# uninstall httpd app and start service -RedHat
  - name: stop service httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family=="RedHat" 
  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family=="RedHat"
 
# uninstall apache2 app and start service - ubuntu
  - name: stop service apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family=="Debian"  
  - name: uninstall apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"


