---
- name: tomcat installation
  hosts: all
  become: true
  tasks:
  - name: install java on redhat servers
    yum:
      name: java
      state: installed
    when: ansible_os_family== "RedHat" 
  - name: Install java on Ubuntu servers
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family== "Debian"
  - name: Download Tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.88/bin/apache-tomcat-8.5.88.tar.gz
      dest: /opt 
  - name: unzip package
    unarchive:
      src: /opt/apache-tomcat-8.5.88.tar.gz
      dest: /opt
      remote_src: yes
  - name: Add execution permissions on startup.sh
    file:
     path: /opt/apache-tomcat-8.5.88/bin/startup.sh
     mode: 0777
  - name: start tomcat server
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.88/bin